#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
chosen=$(cut -d ';' -f1 ~/scripts/emojis | dmenu -i -l 20 | sed "s/ .*//")

[ "$chosen" != "" ] || exit 0

# If you run this command with an argument, it will automatically insert the character.
echo "$chosen" | tr -d '\n' | xclip -selection clipboard
echo "$chosen"
notify-send "$chosen copied to clipboard." &
