#!/bin/bash

SEARCH_ENGINE="https://duckduckgo.com/?q="

q="$(echo | dmenu -c -p "Search the Web:")"

if [ -z "$q" ]; then
    exit 0
elif [[ $q =~ ^https?:\/\/ ]]; then
        brave "${q}"
elif [[ $q =~ (\.co\.uk|\.com|\.net|.io)$ ]]; then
        brave "${q}"
else
        brave "${SEARCH_ENGINE}${q}"
fi
