#!/bin/bash

if [[ $1 == *.pdf ]]
then
        /usr/bin/mupdf $1
elif [[ $1 == *.jpg ]]
then
        /usr/local/bin/sxiv $1
elif [[ $1 == *.jpeg ]]
then
        /usr/local/bin/sxiv $1
elif [[ $1 == *.png ]]
then
        /usr/local/bin/sxiv $1
else
        echo "show: wrong format"
        exit 1
fi
