#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) hib="sudo -A zzz" ;;
	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
esac

cmds="\
lock		slock
leave dwm	kill -TERM $(pidof -s dwm)
renew dwm	kill -HUP $(pidof -s dwm)
suspend	${hib:-sudo -A pm-suspend ; notify-send "Suspending..." && i3lock-fancy}
reboot	${reb:-sudo -A reboot}
shutdown	${shut:-sudo -A shutdown -h now}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu -c -l 10 -i -p "sys:")" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
